### PR TITLE
完成作業，麻煩老師檢查作業是否有問題~

### PR DESCRIPTION
**Pull request by WuRocky**
http://35.74.113.149:3000/api/attractions
http://35.74.113.149:3000/api/attractions?page=1
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E9%A4%8A%E7%94%9F%E6%BA%AB%E6%B3%89
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.74.113.149:3000/api/attractions/10
http://35.74.113.149:3000/api/categories

兩個程式內容
1.mysql_server.py
直接搜尋json內容，建立兩個 table 分別是 data 存放所以資料 categories 存放景點分類，上傳到 ec2 的執行程式讓 mysql 可以運作 

2.app.py
分別是 (1)attractions_API (2) attractions_id_API (3) categories

(1) 我先搜尋數據庫12筆資料，看 page 輸入的數字決定要從第幾筆開始和結束，如果最後一頁不等於12筆資料 nextPage 顯示None。
keyword 我把指定頁搜尋到的資料從 databases 拿出來，分別跟比對模糊查詢(景點名稱)跟完整查詢(景點分類)，然後對資料庫搜尋出來的最後一筆資料 id 跟每頁 keyword 最後一筆資料 id 做對比，如果不相同顯示還有下一頁，如果上最後一筆資料 id 跟每頁 keyword 最後一筆資料相同 nextPage 顯示 None。

(2) 網址輸入的號碼跟 database 做查詢取資料。
(3) 有作景點分類的 table 直接搜尋資料庫的內容。

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review explicitly from the right side in this page.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Format of attraction data is totally incorrect.
2. We should use keyword to filter all attractions and paginate them. If there are 14 attractions after filtering, we get only 2 pages. If there are 4 attractions after filtering, we get only 1 page containing all of these 4 attractions.

**Comment by WuRocky** [comment]
http://35.74.113.149:3000/api/attractions
http://35.74.113.149:3000/api/attractions?page=1
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E9%A4%8A%E7%94%9F%E6%BA%AB%E6%B3%89
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.74.113.149:3000/api/attractions/10
http://35.74.113.149:3000/api/categories

(1)Revise api code
(2)Revise api keyword
(3)Revise mysql data

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues listed below, re-request review after fixing them.

1. Response format of http://35.74.113.149:3000/api/attractions/10 is incorrent.
2. Your code will get unfiltered attraction data, even if we want to get keyword filtered data actually. It's an expensive waste. Use if ... else to make your code logic clear.

**Comment by WuRocky** [comment]
http://35.74.113.149:3000/api/attractions
http://35.74.113.149:3000/api/attractions?page=1
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E9%A4%8A%E7%94%9F%E6%BA%AB%E6%B3%89
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.74.113.149:3000/api/attractions/10
http://35.74.113.149:3000/api/categories

(1) attractions_id_API 
Modify the attractions_id_API path data information。
(2) attractions_API
I modified unnecessary code，Use the page and keywords entered in the URL to choose the way to search the database。

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of http://35.74.113.149:3000/api/attractions/10 is still incorrect.

**Comment by WuRocky** [comment]
http://35.74.113.149:3000/api/attractions
http://35.74.113.149:3000/api/attractions?page=1
http://35.74.113.149:3000/api/attractions?page=0&keyword=%E9%A4%8A%E7%94%9F%E6%BA%AB%E6%B3%8http://35.74.113.149:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.74.113.149:3000/api/attractions/10
http://35.74.113.149:3000/api/categories
(1) attractions_id_API
fetchone data from databases ，change the list of data into a dictionary。
I myself need have to pay attention to the API specification!!!!!!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
